### ISSUE TITLE
elseif keyword not coloured

### ISSUE THREAD

**Issue by shannonfenn** [lteu/minizinc-sublimetext#1]
Thank you for this language definition, it has been very helpful in learning MiniZinc!

One note:
The "elseif" keyword isn't coloured and appears to be missing in the tmLanguage files. It isn't included in the test model which may need updating too.

**Comment by shannonfenn** [comment]
"exists" is also missing fyi.

**Comment by lteu** [comment]
Thanks for your contribution! 
If you agree, I’d like to share this project with and we can modify it together.

Tong

**Comment by shannonfenn** [comment]
Hi Tong,
That sounds great!

**Comment by lteu** [comment]
Could you give me your email address,
or account name, in this way, I may add you to the project.

Tong

**Comment by lteu** [comment]
keyword "exists"  updated.
"elseif" should be written as "else if" please refer to the page 72 of Minizinc tutorial.
